# Generated by Django 3.0.8 on 2020-08-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero_conta', models.CharField(max_length=100, unique=True)),
                ('telefone_1', models.CharField(max_length=50, unique=True)),
                ('telefone_2', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoDevolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=11, unique=True)),
                ('descricao', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Motivo de Devolucao',
                'verbose_name_plural': 'Motivos de Devolucao',
            },
        ),
        migrations.CreateModel(
            name='Emitente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero_conta', models.CharField(max_length=100, unique=True)),
                ('telefone_1', models.CharField(max_length=50, unique=True)),
                ('telefone_2', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('P', 'Particular'), ('E', 'Empresa')], max_length=1)),
                ('assinante', models.ManyToManyField(blank=True, to='core.Assinante')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=50, unique=True)),
                ('numero_conta', models.CharField(max_length=100, unique=True)),
                ('valor_cheque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_devolucao', models.DateTimeField(auto_now_add=True)),
                ('codigo_balcao', models.CharField(max_length=100)),
                ('estado_cheque', models.CharField(choices=[('Devolvido', 'Devolvido'), ('Cancelado', 'Cancelado'), ('Regularizado', 'Regularizado')], default='Devolvido', max_length=50)),
                ('emitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Emitente')),
                ('motivo_devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MotivoDevolucao')),
            ],
        ),
    ]
