# Generated by Django 3.0.8 on 2020-07-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero_conta', models.CharField(max_length=100, unique=True)),
                ('telefone_1', models.CharField(max_length=50, unique=True)),
                ('telefone_2', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emitente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero_conta', models.CharField(max_length=100, unique=True)),
                ('telefone_1', models.CharField(max_length=50, unique=True)),
                ('telefone_2', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('tipo_cliente', models.CharField(choices=[('Empresa', 'Empresa'), ('Singular', 'Singular')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoDevolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=11, unique=True)),
                ('descricao', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Assinante')),
                ('emitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Emitente')),
            ],
        ),
    ]
