# Generated by Django 3.0.8 on 2020-08-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
