# Generated by Django 3.0.8 on 2020-07-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chequedevolvido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emitente',
            old_name='tipo_cliente',
            new_name='tipo_emitente',
        ),
    ]
