# Generated by Django 3.0.8 on 2020-08-18 10:04

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200817_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularizacao',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.regularizacao_file_path),
        ),
    ]
